services:
  web:
    container_name: vsm-http-listener
    build: .
    ports:
      - "8080:80"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
