common:
  port: 8080 # port, our app will use
zabbix:
  server: 10.250.10.30 # zabbix server we're using
  port: 10051 # zabbix port
  interval: 60 # interval between sending updates to server
  host: FaceID # how to impersonate host at zabbix
  key: FaceID.Terminals.Info # key to send value to
